### ISSUE TITLE
[Recent Documents]: when opening a previously played video (.mp4) with vlc, video plays fine, but system is frozen until you close vlc. error message then is 'KDEInit could not launch '/usr/lib/kf5/kioexec'

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.5#10]

**Comment by star-buck** [comment]
observing also while frozen, that taskmanager does not initialize a task in taskbar while vlc is running.

**Comment by star-buck** [comment]
this is normal taskmanager, not EITM or IOTM.

**Comment by eikehein** [comment]
From where is it opened? Kicker, VLC Task Manager button, ...?

**Comment by eikehein** [comment]
Also: Where does the video file reside, normal local folder or special folder like desktop:/ or smb:/? (It's relevant to how URLs get handled when passing to non-kio apps like VLC.)

**Comment by star-buck** [comment]
What happens for you when you open a video file from Recent Documents in
vlc? Does it work?

**Comment by eikehein** [comment]
It works fine here in a simple test, but:

- We have a lot of different Recent Documents entry points now (Kicker menu sections, context menus for apps in Kicker, context menus for Task Manager launchers, the KRunner search plugin, ...)
- The quoted error happens in KIO and the KIO behavior can be quite complex depending on the app being lauched (what URL support does it indicate in its .desktop file, etc.) and the file location

So I need some more info for a good test case / to think about the problem more. I have some hunches, but I need to confirm/disconfirm them :)

**Comment by eikehein** [comment]
Video footage of basic test (local file, standard folder): http://www.eikehein.com/vlc.mkv

**Comment by star-buck** [comment]
Okay, it doesnt work here with local files, neither on desktop or smb://.
Kicker, Kickoff, any menu its all the same.

**Comment by star-buck** [comment]
Local files under /home/Download and being video-filetypes associated to
open in vlc, that is.

**Comment by eikehein** [comment]
I looked into this today and I think it's a bug in KIO that got fixed in Frameworks 5 (we dealt with something very similar showing up in Folder View at the time). Which KF5 / KIO version is installed? If it's 5.15 / 5.16 it might confirm it.

**Comment by star-buck** [comment]
will check with next Manjaro testing ISO, which is supposed to have 5.17.
