### ISSUE TITLE
[discover]: update: when starting an update, then going on "Installed" or "Discover" section and back to "Update", the list is empty and the progress bar is reset.

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.5#13]

**Comment by star-buck** [comment]
the update ist still in progress though it seems, as the progress bar fills itself again...

**Comment by aleixpol** [comment]
Submitted a fix so that we don't get inconsistencies by changing category while upgrading. Could use more work to make it possible.

http://commits.kde.org/discover/4334b5185ba0b9a0e5924e502542d54339e3e546
