### ISSUE TITLE
[netrunner 17 wily]: kio and rootactions-servicemenu conflict

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.5#15]
dpkg: error processing archive /var/cache/apt/archives/kio_5.18.0-0ubuntu1~ubuntu15.10~ppa1_amd64.deb (--unpack):
 trying to overwrite '/usr/share/kservicetypes5/konqpopupmenuplugin.desktop', which is also in package rootactions-servicemenu 2.7.3-0netrunner9
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/kio_5.18.0-0ubuntu1~ubuntu15.10~ppa1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by llelectronics** [comment]
This is basically fixed already in git as we don't ship that file anymore. Though where did you get this kio version from? Anything we have enabled by default in Netrunner 17? 
If yes I will update the package asap. If not we need to keep it for root actions to work for people having the older kio version which does not provide that fix. 
Alternatively we could fix that issue by patching the old kio version aswell if necessary.

**Comment by star-buck** [comment]
?? This is a brand new 17 install and i simply tested the upcoming update of kubuntu wily through backports...

**Comment by star-buck** [comment]
so it IS a problem if you have netrunner 17 installed and simply want to update via backports

**Comment by llelectronics** [comment]
I don't see kio 5.18 in the kubuntu backports ppa that we have enabled by default in Netrunner 17. 
Is this update planned but not pushed ? Is there a eta when it is pushed ?

**Comment by star-buck** [comment]
its backports landing, so it will be in backports shortly (i am testing it before it becomes problems)

**Comment by llelectronics** [comment]
Should be fixed now with new rootactions-servicemenu package and kio package.

**Comment by star-buck** [comment]
please label "ready for QA" then
