### ISSUE TITLE
[netrunner 17 wily backports]: containment error after upgrade

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.5#16]
![p553-desktop-containment-error](https://cloud.githubusercontent.com/assets/840070/12324016/268bc6d4-bac0-11e5-990d-a92eaab60c37.png)

**Comment by llelectronics** [comment]
We already have a branch for netrunner-desktop-containment and plasma 5.5 which is successfully tested on Rolling. 
First test after ppa landing upgrade also shows that it is working. It just needs packaging. 
However we can only release the package after the upgrade to plasma 5.5 landed in kubuntu backports ppa as it isn't compatible with older plasma versions. 

I will package the new version and upload it to our incoming-tmp directory in the repo so as soon as kubuntu backports ppa updates we can very fast and easily push our update out aswell.

**Comment by star-buck** [comment]
We either then need an optional netrunner-backports ppa then as well for
not all users might want to upgrade through backports enabled. Or we copy
and therefore force all packages via our netrunner-17-updates ppa?

**Comment by llelectronics** [comment]
We ship kubuntu backports ppa on by default so I don't see an issue with this as people already received updates from it and want to receive Plasma 5.5.x aswell.

**Comment by llelectronics** [comment]
I think this issue can be closed now as netrunner-desktop-containment 2.0 fixed it

**Comment by star-buck** [comment]
@llelectronics : please label "Ready for QA", ill close when tested and confirmed working
