### ISSUE TITLE
menu: item: add to desktop: if added to netrunner desktop containment, a widget is added of an icon instead

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.5#18]
folderview works, so anything we can do to have it work with netrunner desktop containment?

**Comment by eikehein** [comment]
This would need a small patch to Kicker as shipped by Netrunner (because we have no generic mechanism for it, the Kicker code contains a white list of applets. I can prepare that patch easily, but I'd like to fix it in a better way now that we have the Alternatives/provides system - need to catch Marco to confer ...

**Comment by eikehein** [comment]
I ended up implementing that better solution.

Netrunner now needs:

a) A backport of http://commits.kde.org/plasma-desktop/68c132fa7cf7589ac3b7535699f5128dcda256d1 or a Plasma version shipping it (5.6)

b) Add "X-Plasma-Provides=org.kde.plasma.filemanagement" to the .desktop file of its FV fork

**Comment by llelectronics** [comment]
I tested that with a patched Plasma 5.5.3 package on Netrunner 17(32bit) . It works fine.

**Comment by llelectronics** [comment]
Tested also on 64bit version. Works fine there also. 
Packaged as plasma-desktop_5.5.3-1ubuntu1~ubuntu15.10~ppa4 in Netrunner 17. 
I think we can close this one

**Comment by eikehein** [comment]
So wait are you saying you grabbed the patch? Because that patch is not in 5.5.3 and it's definitely needed for this to work

**Comment by llelectronics** [comment]
Yes I grabbed th patch and applied against Plasma 5.5.3 packages from kubuntu backports.

**Comment by eikehein** [comment]
Ah great, yep then we got it covered.
