### ISSUE TITLE
[scrollbars]: "too slow" when using mouse wheel

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.5#2]
examples:
scrolling down list of "add plasma widgets" or 
inside window decoration kcm when having many themes available

**Comment by star-buck** [comment]
another example is dolphin

**Comment by star-buck** [comment]
comparison dolphin vs. firefox (each time i scrolled down with mousewheel 3 x a full maximum):
https://www.dropbox.com/s/tgorhjvws2ffsvr/scrollwheel.mkv?dl=0

**Comment by mgraesslin** [comment]
Could you try to change: systemsettings -> Input Devices -> Mouse -> Advanced -> "Mouse wheel scrolls by: "

**Comment by star-buck** [comment]
changed it to 12, same issue.

**Comment by mgraesslin** [comment]
ok, given that I assume it's rather the application not being able to scroll fast enough. E.g. in the Dolphin case there were many items visible, though on my system dolphin scrolls extremely fast also with many items as well. For the decoration KCM I'm quite sure that it's related to the lazy loading of the decorations.

**Comment by star-buck** [comment]
Hmmm, while not impossible, it seems very unlikely... The machine is 8GB
almost brandnew and besides new 5.5 Manjaro also old Netrunner 16 on it,
where dolphin scrolls just fine under the same folders. What I can test
tomorrow is simply resize any Qt window and see if even with small number
of items, the scrolling will remain slow/unaffected by the actual settings.

Meanwhile any other ideas what I could test?

**Comment by mgraesslin** [comment]
> Meanwhile any other ideas what I could test?

I have one weird idea: change the window decoration. Maybe for whatever reason scrolling on the window triggers repaints in the deco and slowing down the whole UI. Aurorae is still a little bit heavier with "logical" content behind the window.

**Comment by star-buck** [comment]
its not related to number of items.
also changing the window deco has no effect.
It's generally some qt/qml apps/windows are slow while others are fine, like firefox, kate, system settings, etc.

one more video how it compares:
https://www.dropbox.com/s/vo95jkhxj5r3jgf/scrolling-mousewheel.mkv?dl=0

**Comment by mgraesslin** [comment]
very interesting that video - especially the last part in the add widget dialog. It's clearly not related to the list in any way, it's just the scrolling is slow. For me scrolling in that view is slow either way. It looks like it blocks whenever it needs to create new items. But in Dolphin it's super fast - faster than in Firefox.

I know that there are two ways of scrolling on X11: one through xinput, one through mouse button 4/5 (yes mouse wheel is emulated as mouse button). This could be an explanation, but that clearly needs more investigation.

As we know have the Wayland live iso: comparing to that could be interesting. Also as it allows to run the application as either X11 or Wayland.

**Comment by notmart** [comment]
the scroll speed in Flickable is influenced also by the maximumVerticalFlickVelocity property.. maybe we could tweak it until it shows an acceptable speed?

**Comment by star-buck** [comment]
whats Flickable?

**Comment by notmart** [comment]
The QML element used to do all views that scroll, i'm tracking to see where the wheel event is actually managed

**Comment by notmart** [comment]
the scrolling in that video is done with an actual mouse wheel or with the two finger gesture on a touchpad? i see they seem to be managed differently, and while i can alter the speed of the scroll by mouse wheel (i have to patch QtQuickControls tough, yay!)  scroll by two fingers seems to stay untouched

**Comment by star-buck** [comment]
mouse wheel.
any idea why it did regress recently and why Dolphin is affected but not
others?

**Comment by notmart** [comment]
For QML-retated stuff, I have this Qt patch that may help to solve the issue:
https://codereview.qt-project.org/#/c/145642/

**Comment by star-buck** [comment]
what about dolphin? and kcms like window deco?

**Comment by notmart** [comment]
this is relevant to dolphin https://git.reviewboard.kde.org/r/126718/

**Comment by star-buck** [comment]
so thats supposedly for dolphin. what about scrolling in the wallpaper settings? i wonder why there are several areas where scrolling is fine and others that are affected as of recently, which were fine before. So maybe instead of fixing all those areas singlehandedly, lets find a common cause for all slow, non-qml areas?

**Comment by notmart** [comment]
wallpapers settings (also windows decoration kcm) are in qml, so in that case it would apply https://codereview.qt-project.org/#/c/145642/

**Comment by star-buck** [comment]
ah nice!

**Comment by star-buck** [comment]
which version release would fix the qml and which the dolphin?

**Comment by notmart** [comment]
dolphin with the next applications release, Qt is often very slow to accept changes, if is urgent we may have to carry the patch in the meantime

**Comment by star-buck** [comment]
which Qt would the earliest be?
In the meantime, this is imo serious enough to ship a temp. workaround/fix in next plasma/frameworks release.

**Comment by notmart** [comment]
the qt one just got +2 on the 5.6 branch, so if all goes well the 5.6.0 release should have it

**Comment by star-buck** [comment]
Release eta?

**Comment by mgraesslin** [comment]
> Release eta?

According to https://wiki.qt.io/Qt-5.6-release at Feb 9th. Till it's in distributions it'll be some more time.

**Comment by notmart** [comment]
pasting in the right thread this time :)
patch is merged in 5.6, so will be in 5.6.0 which latest plan is to be released 9th february
https://wiki.qt.io/Qt-5.6-release

**Comment by star-buck** [comment]
Apparently adding xf86-input-libinput is the reason for slowing down the mouse wheel!
Just removing that package brings back scrolling to normal speed. Any input on simply removing this? (maybe @mgraesslin knows?)

**Comment by mgraesslin** [comment]
sorry my knowledge about the Xorg input stack is almost non existent.
