### ISSUE TITLE
netrunner 17: [widget explorer]: remove patched netrunner-version to use 5.5.3 version

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.5#20]
remove the first one below:

netrunner@netrunner-MacBookAir:~$ locate WidgetExplorer
/usr/share/netrunner-default-settings/plasma5-profile/plasma/shells/org.kde.plasma.desktop/contents/explorer/WidgetExplorer.qml

/usr/share/plasma/shells/org.kde.plasma.active/contents/explorer/WidgetExplorer.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/WidgetExplorer.qml
/usr/share/plasma/shells/org.kde.plasma.phone/contents/explorer/WidgetExplorer.qml
netrunner@netrunner-MacBookAir:~$

**Comment by llelectronics** [comment]
Removing this file alone would break the desktop. We have to refresh the org.kde.plasma.desktop folder for this to fix it.

**Comment by llelectronics** [comment]
Fixed now with netrunner-default-settings_1.6.1
