### ISSUE TITLE
[discover]: using discover to update results in endless "apt-check" threads

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.5#22]
![apt-cache](https://cloud.githubusercontent.com/assets/840070/13027410/9be08f4a-d24f-11e5-8633-b8c3267d0f77.png)

**Comment by star-buck** [comment]
not sure why, but i thought its using packagekit/appstream in latest version?

**Comment by aleixpol** [comment]
This should be fixed as this commit, in Plasma/5.5 stable branch:
https://quickgit.kde.org/?p=discover.git&a=commit&h=7ded9bf1de57f7954be552a48aa9abdb3e4db400

You are running the good old QApt backend there. We could start getting APT-based systems using the PackageKit backend though, Tanglu already does.

**Comment by star-buck** [comment]
When is this fix shipped with which version?

@Aleix: Discover is and was your primary assignement since its existence.
It is one of the tools people rely on not to mess up and always work 100%
perfectly and reliably. I do not care for anything else as much you do from
a Blue Systems point of view.
Last call: Make sure it runs absolutely fault free on upcoming neon ISOs
based on Xenial, and also with Thomas help under Plasma Mobile with mobile
view, including our discussed smart, zoomed out way of handling and
presenting software packages and OCS resources like kde-look.org.

**Comment by star-buck** [comment]
@aleixpol : 
Can you do a video of Discover running on your machine with two things:
Open ksysguard showing memory sorted view
Open patched/fixed Discover (dont do any additional patches that would require re-patching at this point) and click on Games, then wait for everything to load, then go back to Home and click Games again, repeat 2x more times and show memory consumtption of ksysguard.

The point is to find out if Netrunner things are somehow borked or its still Discover.

@jriddell : Does the current neon ISO has latest Discover shipped?

**Comment by jriddell** [comment]
Yes package is plasma-discover and today's build is 5.5.3+git20160224.0009+15.10-0

I've had the apt-check bug occasionally but not today so far

**Comment by star-buck** [comment]
@jriddell: is that the latest git master version despite package main version being 5.5.3 instead of 5.5.4?

**Comment by jriddell** [comment]
yes it's from git master

fix the package versions to be more sensible in Neon is still on the todo

**Comment by star-buck** [comment]
@jriddell :
Discover on neon doesnt show any apps inside though, so i cant compare to netrunner.

**Comment by star-buck** [comment]
Here is a video with patched Discover 5.5.4:
https://www.dropbox.com/s/b5r9gaagz8jla5q/discover-RAM.mkv?dl=0

It takes 5-10 seconds clicking + loading a category like Games, pushing it all into RAM.
Going back and clicking the same category once more, it doesnt use the cached RAM, but reloads everything again on top into RAM, leading shortly to a huge memory eating Discover.

**Comment by aleixpol** [comment]
I might be seeing something similar:
https://youtu.be/f547Q_VFSw0

I can look for a way to reduce this loading times and the possible memory leak.

**Comment by star-buck** [comment]
Then please test this also with Qapt backend, it is used by anyone Kubuntu and Netrunner default.

**Comment by aleixpol** [comment]
Both issue you are pointing out here (memory leaking and slow page rendering) are in the front-end.
I already submitted a patch to solve the memory problem (in master, I can backport if you're going to use it), I'm looking if we can save up some page loading time.

**Comment by star-buck** [comment]
You are right, its discover frontend again.

I just tested with purely packagekit based Discover in Rolling, and this is what happens:
https://www.dropbox.com/s/di692ku3v6v0sfs/discover-rolling-latest-version.mkv?dl=0

**Comment by aleixpol** [comment]
Here's a patch that improves the category loading and fixes the memory leak on Plasma 5.5:
http://commits.kde.org/discover/994f7552a136c54cc5a2e5e4f9d52e50e5a54105

**Comment by star-buck** [comment]
@aleixpol : please provide info on which release this is fixed with which package and mark anything you are assigned to "Ready for QA" while still waiting for the official release.

**Comment by aleixpol** [comment]
Should be fixed as of Plasma 5.5.5: https://www.kde.org/info/plasma-5.5.5.php
