### ISSUE TITLE
[menu recent apps]: doesnt show last used program at top consistently

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.5#3]
https://www.dropbox.com/s/jfpyoqs7qhtt1po/vokoscreen-2015-12-14_20-25-21.mkv?dl=0

**Comment by eikehein** [comment]
Can we add Ivan to this ticket or should I speak to him manually? (The sorting happens in KActivities.)

**Comment by star-buck** [comment]
reopened another ticket for plasma 5.8, closing here.
