### ISSUE TITLE
[muon-updater]: weird info when last updated

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.5#5]
after full update finished, info shows this:
![muon-updater](https://cloud.githubusercontent.com/assets/840070/11798701/34297c7c-a2c5-11e5-8aef-7dcc1e463e69.png)

**Comment by aleixpol** [comment]
Fixed in Plasma 5.5 branch.
http://commits.kde.org/discover/abc04a52618cd9a4be40a3ea3a2b4e79069930ff
