### ISSUE TITLE
[discover]: allow grab and drag list up and down again (instead of using scrollbar)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.5#7]

**Comment by notmart** [comment]
this for both desktop and mobile? just mobile?
@aleixpol , did you explicitly disable it or is done i guess by the scrollview component?

**Comment by star-buck** [comment]
desktop and mobile, both should be consistent

**Comment by aleixpol** [comment]
Qt Quick Controls prevents that explicitly.

I'm not sure it's really about consistency there, in fact it will just work on touch screens as well, since a mouse click and a tap event aren't exactly the same.

**Comment by notmart** [comment]
also, just built discover from master.. i see that pretty much everywhere i can scroll both by drag and wheel.. *but* that is on a laptop with touchscreen, that may influence the behavior?

**Comment by star-buck** [comment]
It was working before and for consistency it should work again.
Please see that it does and is enabled default.

**Comment by aleixpol** [comment]
@notmart Scroll wheel always worked, what @star-buck wants is to scroll by click and drag.

**Comment by star-buck** [comment]
like the dashboard menu does e.g.
