### ISSUE TITLE
[kamoso]: show time elapsed when taking video until stopped

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.5#9]

**Comment by aleixpol** [comment]
As an on-screen display? Wouldn't it maybe make more sense to show the video length on the gallery?

**Comment by star-buck** [comment]
No, why? Every video recorder/ program shows time elapse while recording...

**Comment by aleixpol** [comment]
Introduced the OSD as initially suggested:
http://commits.kde.org/kamoso/0a1bec872815d3fea9f5673a511f92f517176dbc

Will be part of the next major release as it includes some new strings.

**Comment by star-buck** [comment]
reminder: please mark anything fixed with green packaging label.

**Comment by star-buck** [comment]
@aleixpol : which release should this be in?

**Comment by aleixpol** [comment]
I uploaded new release tarballs yesterday, waiting on the sysadmins, we'll have a final release by next week.

**Comment by aleixpol** [comment]
Final release tarballs updated https://userbase.kde.org/Kamoso/3.2

**Comment by star-buck** [comment]
done with 3.2
